#
# Builds project on Appveyor <http://www.appveyor.com/>
#

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-32bit.7z"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-64bit.7z"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-32bit.7z"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-64bit.7z"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-32bit.7z"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017 Win64"
      CONFIG: Release
      SDK_URL: "http://resource.osvr.com/public_download/OSVR-Core/OSVR-Core-Snapshot-latest-64bit.7z"


install:
  - ps: Start-FileDownload "${env:SDK_URL}"
  - ps: 7z x OSVR-Core-Snapshot-latest-*bit.7z
  - ps: move OSVR-Core-Snapshot-* c:\osvr


# TODO set up cache for dependencies

# build dependencies
before_build:

build:
  parallel: true

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="c:\osvr" -DCMAKE_PREFIX_PATH="c:\osvr" -Dosvr_DIR="C:\osvr\lib\cmake\osvr" -DBUILD_HEADER_DEPENDENCY_TESTS=1  -DBUILD_APPS=1 -DBUILD_TESTS=1
  - cmake --build . --config "%CONFIG%" --target install
  - ctest --build-config %CONFIG% --extra-verbose

# Enable RDP access
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Keep an RDP connection open after the build has finished
# until the lock file on the desktop is removed.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

