#
# Builds project on Appveyor <http://www.appveyor.com/>
#

environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release
    - GENERATOR: "Visual Studio 12 2013 Win64"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release
    - GENERATOR: "Visual Studio 14 2015 Win64"
      CONFIG: Release

# Enable RDP access
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


install:
  - ps: Start-FileDownload 'http://access.osvr.com/binary/download/builds/OSVR-Installer-Win-DEV/OSVR-SDK-v0.6-1317-g80ee6b5-build198-win-64bit.msi'
  - ps: .\OSVR-SDK-v0.6-1317-g80ee6b5-build198-win-64bit.msi /quiet /norestart

# TODO set up cache for dependencies

# build dependencies
before_build:

build:
  parallel: true

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake .. -G "%GENERATOR%" -DCMAKE_INSTALL_PREFIX="c:\osvr" -DCMAKE_PREFIX_PATH="c:\osvr" -DBUILD_HEADER_DEPENDENCY_TESTS=1  -DBUILD_CLIENT_APPS=1 -DBUILD_TESTS=1
  - cmake --build . --config "%CONFIG%" --target install

# TODO run tests and integrate with AppVeyor dashboard

# Keep an RDP connection open after the build has finished
# until the lock file on the desktop is removed.
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

